export const USER_LOGIN_AUTHENTICATION = 'USER_LOGIN_AUTHENTICATION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_LOADING = 'SET_LOADING';
export const USER_NOT_LOGGEDIN = 'USER_NOT_LOGGEDIN';
export const STORE_ATTRIBUTES = 'STORE_ATTRIBUTES';
export const FETCH_ALL_DATA = 'FETCH_ALL_DATA';
export const GET_PREDICTION = 'GET_PREDICTION';
